language: go

go:
  - "1.13"
  - "1.14"

dist: xenial
sudo: required

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - sudo chmod 666 /dev/uinput
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
